title: Ali's Blog
email: ali@faraji.info
description: >- # this means to ignore newlines until "baseurl:"
  (Not limited to) CS & Math stuff

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.faraji.info" # the base hostname & protocol for your site, e.g. http://example.com

# social links
#twitter_username: AliFaraji98
github_username:  alifa98
rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: alifaraji98
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"


# For comment system
#comments: true
#disqus:
#  shortname: faraji

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# enable toc by default
defaults:
  - scope:
      path: ""
    values:
      toc: true

toc:
  min_level: 1
  max_level: 4
  ordered_list: false
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: section-nav
  sublist_class: ''
  item_class: toc-entry
  item_prefix: toc-

# Build settings
markdown: kramdown

theme: minima
plugins:
 - jekyll-toc
 - jekyll-feed
 - jekyll-seo-tag
